# Generated by Django 5.2.8 on 2025-11-12 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='needs',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
