# Generated by Django 5.2.8 on 2025-11-12 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0002_booking_qrcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='qr_code',
        ),
        migrations.AddField(
            model_name='booking',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='scanned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
